
bc_settings.admin_settings_form:
  path: '/admin/config/bc_settings/adminsettings'
  defaults:
    _form: '\Drupal\bc_settings\Form\AdminSettingsForm'
    _title: 'AdminSettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

