bc_settings.admin_settings_form:
  title: 'Settings'
  route_name: bc_settings.admin_settings_form
  description: 'Manage this websites custom settings'
  parent: system.admin_config_system
  weight: 99

